src/Entity/Hike.php
<?php

namespace App\Entity;

use App\Repository\HikeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: HikeRepository::class)]
class Hike
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    #[Groups('hike:read')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    #[Groups('hike:read')]
    private $name;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Groups('hike:read')]
    private $Content;

    #[ORM\Column(type: 'float', nullable: true)]
    #[Groups('hike:read')]
    private $length;

    #[ORM\Column(type: 'float', nullable: true)]
    #[Groups('hike:read')]
    private $duration;

    #[ORM\Column(type: 'float', nullable: true)]
    #[Groups('hike:read')]
    private $elevation_gain;

    #[ORM\Column(type: 'float', nullable: true)]
    #[Groups('hike:read')]
    private $elevation_loss;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Groups('hike:read')]
    private $gps_coordonate;

    #[ORM\ManyToOne(targetEntity: Difficulty::class, inversedBy: 'hikes')]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups('hike:read')]
    private $difficulty;

    #[ORM\OneToMany(mappedBy: 'hike', targetEntity: HikeImages::class)]
    #[Groups('hike:read')]
    private $hikeImages;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Groups('hike:read')]
    private $nameSlugger;

    public function __construct()
    {
        $this->hikeImages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getLength(): ?float
    {
        return $this->length;
    }

    public function setLength(?float $length): self
    {
        $this->length = $length;

        return $this;
    }

    public function getDuration(): ?float
    {
        return $this->duration;
    }

    public function setDuration(?float $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getElevationGain(): ?float
    {
        return $this->elevation_gain;
    }

    public function setElevationGain(?float $elevation_gain): self
    {
        $this->elevation_gain = $elevation_gain;

        return $this;
    }

    public function getElevationLoss(): ?float
    {
        return $this->elevation_loss;
    }

    public function setElevationLoss(?float $elevation_loss): self
    {
        $this->elevation_loss = $elevation_loss;

        return $this;
    }

    public function getGpsCoordonate(): ?string
    {
        return $this->gps_coordonate;
    }

    public function setGpsCoordonate(?string $gps_coordonate): self
    {
        $this->gps_coordonate = $gps_coordonate;

        return $this;
    }

    public function getDifficulty(): ?Difficulty
    {
        return $this->difficulty;
    }

    public function setDifficulty(?Difficulty $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    /**
     * @return Collection<int, HikeImages>
     */
    public function getHikeImages(): Collection
    {
        return $this->hikeImages;
    }

    public function addHikeImage(HikeImages $hikeImage): self
    {
        if (!$this->hikeImages->contains($hikeImage)) {
            $this->hikeImages[] = $hikeImage;
            $hikeImage->setHike($this);
        }

        return $this;
    }

    public function removeHikeImage(HikeImages $hikeImage): self
    {
        if ($this->hikeImages->removeElement($hikeImage)) {
            // set the owning side to null (unless already changed)
            if ($hikeImage->getHike() === $this) {
                $hikeImage->setHike(null);
            }
        }

        return $this;
    }

    public function getNameSlugger(): ?string
    {
        return $this->nameSlugger;
    }

    public function setNameSlugger(?string $nameSlugger): self
    {
        $this->nameSlugger = $nameSlugger;

        return $this;
    }
}

src/Controller/RandonneeController.php
<?php

namespace App\Controller;

use App\Entity\Hike;
use App\Repository\HikeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


class RandonneeController extends AbstractController
{
    #[Route('/randonnee', name: 'app_randonnee')]
    public function index(): Response
    {
        return $this->render('randonnee/index.html.twig', [
            'controller_name' => 'RandonneeController',
        ]);
    }

    #[Route('/randonnee_facile', name: 'randonnee_facile')]
    public function randonneeFacile(): Response
    {
        return $this->render('randonnee/randonneeFacile.html.twig', [
            'controller_name' => 'randonneeFacile',
        ]);
    }
    #[Route('/randonnee_moyenne', name: 'randonnee_moyenne')]
    public function randonneeMoyenne(): Response
    {
        return $this->render('randonnee/randonneeMoyenne.html.twig', [
            'controller_name' => 'randonneeMoyenne',
        ]);
    }
    #[Route('/randonnee_difficile', name: 'randonnee_difficile')]
    public function randonneeDifficile(): Response
    {
        return $this->render('randonnee/randonneeDifficile.html.twig', [
            'controller_name' => 'randonneeDifficile',
        ]);
    }

    #[Route('/randonneeFetchRender', name: 'randonneeFetchRender', methods: ['GET'])]
    public function randonneeFetchRender(HikeRepository $hikeRepository, NormalizerInterface $normalizer): Response
    {
        return $this->json($normalizer->normalize($hikeRepository->findAll(), null, ['groups' => 'hike:read']));
    }

    #[Route('/{nameSlugger}', name: 'randonne_detail_show', methods: ['GET'])]
    public function show(Hike $hike): Response
    {
        return $this->render('randonnee/randonneeDetail.html.twig', [
            'hike' => $hike,
        ]);
    }
}

templates/randonnee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Randonnées{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style_randonnees.css') }}">
{% endblock %}

{% block body %}
<main class="main">
    <section class="hero_randonnees"></section>
    <div class="nous_suivre">
        <p class="para_noussuivre">NOUS SUIVRE</p>
        <a href=""><img src='{{ asset("img/facebook-48.png") }}' alt="icone Facebook" class="icones_noussuivre"></a>
        <a href=""><img src='{{ asset("img/instagram-48.png") }}' alt="icone Instagram" class="icones_noussuivre"></a>
    </div>

    <section class="background_beige">
        <p class="trouver">Trouver votre rando en trois étapes !</p>
        <section class="etapes wrapper_etapes">
            <div class="etape_1 shadow_white">
                <img src='{{ asset("img/number-one_icon-icons.com_66514.png") }}' alt="icone étape numero 1" class="numero_etapes">
                <p class="para_etape">Lire le descriptif ci-dessous de chaque niveau, puis sélectionner celui qui est le plus adaptés à votre condition physique.<br><br> En cas de doute, nous vous conseillons de choisir un niveau en dessous.</p>
            </div>

            <div class="etape_2 shadow_white">
                <img src='{{ asset("img/number-two_icon-icons.com_66513.png") }}' alt="icone étape numero 2" class="numero_etapes">
                <p class="para_etape">Une fois votre niveau choisi, vous pouvez cliquer sur le bouton Fiches Rando correspondant à votre condition afin d'être redirigé vers des randonnées vous correspondant.<br><br>
                    Chaque niveau est représenté par une icône de couleur :</p>

                <section class="flex_icone">
                    <div>
                        <img src='{{ asset("img/icone2.png") }}' alt="image icone niveau facile" class="icones">
                        <p class="style-text-icone">Niveau facile</p>
                    </div>

                    <div class="margin-cotes">
                        <img src='{{ asset("img/icone1.png") }}' alt="image icone niveau moyen" class="icones">
                        <p class="style-text-icone">Niveau moyen</p>
                    </div>

                    <div>
                        <img src='{{ asset("img/icone3.png") }}' alt="image icone niveau difficile" class="icones">
                        <p class="style-text-icone">Niveau difficile</p>
                    </div>
                </section>
            </div>

            <div class="etape_3 shadow_white">
                <img src='{{ asset("img/number-three_icon-icons.com_66512.png") }}' alt="icone étape numero 3" class="numero_etapes">
                <p class="para_etape">Vous avez fait votre choix ? <br><br>vous pouvez dès à présent sélectionner des randonnées en toute sérénité!<br><br> Bonne rando! </p>
            </div>
        </section>
    </section>

    <!-- <section class="gallerie_img">
        <img src="assets/img/gallerie1.png" alt="" class="img_gallerie">
        <img src="assets/img/gallerie2.png" alt="" class="img_gallerie">
        <img src="assets/img/gallerie3.png" alt="" class="img_gallerie">
        <img src="assets/img/gallerie4.png" alt="" class="img_gallerie">
    </section> -->

    <section class="contener_niveaux">
        <p class="texte_niveau">Maintenant à vous de choisir !</p>
        <section class="wrapper_niveaux les_niveaux">
            <div class="niveau_facile color_backgrd1">
                <img src='{{ asset("img/icone2.png") }}' alt="image icone niveau facile" class="icones_choix">
                <p class="vert">NIVEAU FACILE</p>
                <p class="vert separateur">Pour qui ?</p>
                <div class="taille_para">
                    <p class="cond_descr1">DESCRIPTION :</p>
                    <p class="text-style">Sentiers larges et bien entretenus, avec des pentes peu soutenues. <br>Idéal pour les promenades en famille.</p>
                    <p class="cond_descr1">CONDITION PHYSIQUE:</p>
                    <p class="text-style">Je suis en forme. Je pratique une activité sportive occasionnellement.</p>
                    <a href="randonnee_facile" class="bouton">Fiches Rando</a>
                </div>
            </div>

            <div class="niveau_moyen marge_lr color_backgrd2">
                <img src='{{ asset("img/icone1.png") }}' alt="icone facile" class="icones_choix">
                <p class="bleu">NIVEAU MOYEN</p>
                <p class="bleu separateur">Pour qui ?</p>
                <div class="taille_para">
                    <p class="cond_descr2">DESCRIPTION :</p>
                    <p class="text-style">Sentiers de montagne confortables ne présentant pas de grosses difficultés techniques.
                        Parcours idéal pour la découverte de la randonnée sur un ou plusieurs jours</p>
                    <p class="cond_descr2">CONDITION PHYSIQUE:</p>
                    <p class="text-style">J'ai une condition physique correcte. Je pratique une activité sportive régulièrement. J’aime me dépasser sur des efforts pas trop longs et j’ai besoin de repos entre les activités. Je pratique une activité sportive occasionnellement.</p>
                    <a href="randonnee_moyenne" class="bouton">Fiches Rando</a>
                </div>
            </div>

            <div class="niveau_difficile color_backgrd3">
                <img src='{{ asset("img/icone3.png") }}' alt="icone facile" class="icones_choix">
                <p class="rouge">NIVEAU DIFFICILE</p>
                <p class="rouge separateur">Pour qui ?</p>
                <div class="taille_para">
                    <p class="cond_descr1">DESCRIPTION :</p>
                    <p class="text-style">Terrains de montagne variés pouvant présenter des difficultés techniques (passages aménagés et sécurisés, courtes portions d’échelles) ou des passages exposés au vide. Elle peut se dérouler hors des sentiers et sur des terrains difficiles type pierriers.</p>
                    <p class="cond_descr1">CONDITION PHYSIQUE:</p>
                    <p class="text-style">Je suis en forme. J'ai une très bonne condition physique. Je pratique une activité sportive plusieurs fois par semaine. J’ai l’envie de me dépasser sur des efforts longs et je peux endurer la fatigue dans une certaine mesure.</p>
                    <a href="randonnee_difficile" class="bouton">Fiches Rando</a>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

templates/randonnee/randonneeDetail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style_rando-fmd.css') }}">
{% endblock %}


{% block body %}
    <main>
        <section class="hero_facile"></section>
        <div class="nous_suivre">
            <p class="para_noussuivre">NOUS SUIVRE</p>
            <a href=""><img src='{{ asset("img/facebook-48.png") }}' alt="icone Facebook" class="icones_noussuivre"></a>
            <a href=""><img src='{{ asset("img/instagram-48.png") }}' alt="icone Instagram" class="icones_noussuivre"></a>
        </div>

{#        <section>#}
{#            <img src='{{ asset("img/icone_vert.png") }}' alt="icone rando facile" class="icone_facile">#}
{#            <div class="titre_niveau">#}
{#                <a href="randonnee_difficile"><img src='{{ asset("img/flechel.png") }}' class="flechel" title="voir le niveau difficile"></a>#}
{#                <p class="para_titre">Niveau facile</p>#}
{#                <a href="randonnee_moyenne"><img src='{{ asset("img/flecher.png") }}' class="flecher" title="voir le niveau moyen"></a>#}
{#            </div>#}
{#        </section>#}

        <section class="center">
            <section class="grid_rando">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Nom</th>
                        <td>{{ hike.name }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ hike.Content }}</td>
                    </tr>
                    <tr>
                        <th>Distance</th>
                        <td>{{ hike.length }}</td>
                    </tr>
                    <tr>
                        <th>Durée</th>
                        <td>{{ hike.duration }}</td>
                    </tr>
                    <tr>
                        <th>Dénivelée positif</th>
                        <td>{{ hike.elevationGain }}</td>
                    </tr>
                    <tr>
                        <th>Dénivelée négatif</th>
                        <td>{{ hike.elevationLoss }}</td>
                    </tr>
                    <tr>
                        <th>Coordonnées GPS</th>
                        <td>{{ hike.gpsCoordonate }}</td>
                    </tr>
                    </tbody>
                </table>

                <a href="{{ path('app_randonnee') }}">Retour à la liste</a>
            </section>
        </section>
    </main>
    {% endblock %}

templates/randonnee/randonneeDifficile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Randonnées Difficile{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style_rando-fmd.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# appel de notre rendu react #}
    <script>const LEVEL="difficile";</script>
    {{ encore_entry_script_tags('js/randosNiveauRender') }}
{% endblock %}

{% block body %}
    <main>
        <section class="hero_difficile"></section>
        <div class="nous_suivre">
            <p class="para_noussuivre">NOUS SUIVRE</p>
            <a href=""><img src='{{ asset("img/facebook-48.png") }}' alt="icone Facebook" class="icones_noussuivre"></a>
            <a href=""><img src='{{ asset("img/instagram-48.png") }}' alt="icone Instagram" class="icones_noussuivre"></a>
        </div>

        <section>
            <img src='{{ asset("img/icone_rouge.png") }}' alt="icone rando difficile" class="icone_facile">
            <div class="titre_niveau">
                <a href="randonnee_moyenne"><img src='{{ asset("img/flechel.png") }}' class="flechel" title="voir le niveau moyen"></a>
                <p class="para_titre">Niveau Difficile</p>
                <a href="randonnee_facile"><img src='{{ asset("img/flecher.png") }}' class="flecher" title="voir le niveau facile"></a>
            </div>
        </section>

        <section class="center">
            <section id="randoDisplay" class="grid_rando">

            </section>
        </section>
    </main>
{% endblock %}

templates/randonnee/randonneeFacile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Randonnées Facile{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style_rando-fmd.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# appel de notre rendu react #}
    <script>const LEVEL="facile";</script>
    {{ encore_entry_script_tags('js/randosNiveauRender') }}
{% endblock %}

{% block body %}
    <main>
        <section class="hero_facile"></section>
        <div class="nous_suivre">
            <p class="para_noussuivre">NOUS SUIVRE</p>
            <a href=""><img src='{{ asset("img/facebook-48.png") }}' alt="icone Facebook" class="icones_noussuivre"></a>
            <a href=""><img src='{{ asset("img/instagram-48.png") }}' alt="icone Instagram" class="icones_noussuivre"></a>
        </div>

        <section>
            <img src='{{ asset("img/icone_vert.png") }}' alt="icone rando facile" class="icone_facile">
            <div class="titre_niveau">
                <a href="randonnee_difficile"><img src='{{ asset("img/flechel.png") }}' class="flechel" title="voir le niveau difficile"></a>
                <p class="para_titre">Niveau facile</p>
                <a href="randonnee_moyenne"><img src='{{ asset("img/flecher.png") }}' class="flecher" title="voir le niveau moyen"></a>
            </div>
        </section>

        <section class="center">
            <section id="randoDisplay" class="grid_rando">

            </section>
        </section>
    </main>
    {% endblock %}

templates/randonnee/randonneeMoyenne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les Randonnées Moyenne{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style_rando-fmd.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# appel de notre rendu react #}
    <script>const LEVEL="moyen";</script>
    {{ encore_entry_script_tags('js/randosNiveauRender') }}
{% endblock %}

{% block body %}
    <main>
        <section class="hero_moyen"></section>
        <div class="nous_suivre">
            <p class="para_noussuivre">NOUS SUIVRE</p>
            <a href=""><img src='{{ asset("img/facebook-48.png") }}' alt="icone Facebook" class="icones_noussuivre"></a>
            <a href=""><img src='{{ asset("img/instagram-48.png") }}' alt="icone Instagram" class="icones_noussuivre"></a>
        </div>

        <section>
            <img src='{{ asset("img/icone_bleu.png") }}' alt="icone rando moyenne" class="icone_facile">
            <div class="titre_niveau">
                <a href="randonnee_facile"><img src='{{ asset("img/flechel.png") }}' class="flechel" title="voir le niveau facile"></a>
                <p class="para_titre">Niveau Moyen</p>
                <a href="randonnee_difficile"><img src='{{ asset("img/flecher.png") }}' class="flecher" title="voir le niveau difficile"></a>
            </div>
        </section>

        <section class="center">
            <section id="randoDisplay" class="grid_rando">

            </section>
        </section>
    </main>
    {% endblock %}